package com.mindtree;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;

public class QuizApp {

	public static void main(String[] args) throws IOException, SQLException {
		String url = "jdbc:mysql://localhost:3306/quizapp";
		String userid = "root";
		String passwordid = "Welcome123";
		Connection conn = null;
		try {
			conn = DriverManager.getConnection(url, userid, passwordid);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		String user = "", password = "";
		int choice;
		int truecount = 0;
		int falsecount = 0;
		Scanner scanner = new Scanner(System.in);
		BufferedReader keyboardInput;
		keyboardInput = new BufferedReader(new InputStreamReader(System.in));
		System.out.println("Kindly login");
		System.out.print("User:");
		user = scanner.next();
		System.out.print("Password:");
		password = scanner.next();
		if (user.equals("shivam") && password.equals("12345")) {
			System.out.println("Select your role:\n" + "1.Admin\n" + "2.Quiz Master\n" + "3.Participants");
			System.out.print("your choice:");
			choice = scanner.nextInt();
			if (choice == 1 || choice == 2 || choice == 3) {
				if (choice == 1) {
					System.out.println("You are logged as admin");
					System.out.println("1.Add question\n2.Delete question");
					System.out.println("Enter your choice:");
					int ch = scanner.nextInt();
					if (ch == 1) {
						System.out.println("Enter question details");
						String ques, opt1, opt2, opt3, opt4, correct;
						System.out.print("enter question:");
						ques = keyboardInput.readLine();
						System.out.print("enter option1:");
						opt1 = keyboardInput.readLine();
						System.out.print("enter option2:");
						opt2 = keyboardInput.readLine();
						System.out.print("enter option3:");
						opt3 = keyboardInput.readLine();
						System.out.print("enter option4:");
						opt4 = keyboardInput.readLine();
						System.out.print("enter correct answer:");
						correct = keyboardInput.readLine();
						try {

							PreparedStatement ps = (PreparedStatement) conn.prepareStatement(
									"INSERT INTO question (qid,ques,opt1,opt2,opt3,opt4,correct) VALUES (?, ?, ?, ?, ?, ?, ?)");

							int autoGeneratedID = 0;

							ps.setInt(1, autoGeneratedID);
							ps.setString(2, ques);
							ps.setString(3, opt1);
							ps.setString(4, opt2);
							ps.setString(5, opt3);
							ps.setString(6, opt4);
							ps.setString(7, correct);

							ps.executeUpdate();
							System.out.println("Question added successfully.");

						} catch (SQLException e) {
							e.printStackTrace();
						}
					} else if (ch == 2) {
						System.out.println("enter question id of question you want to delete:");
						int did = scanner.nextInt();
						Statement stmt = (Statement) conn.createStatement();
						String query = "delete from question where qid='" + did + "'";
						int result = stmt.executeUpdate(query);
						if (result == 0) {
							System.out.println("record not found to delete");
						} else {
							System.out.println(result + " no.of record(s) found and deleted");
						}
						stmt.close();

					}
				}

				if (choice == 2) {
					System.out.println("you are logged as quiz master.");
				}

				if (choice == 3) {
					System.out.println("you are logged as participant.");
					System.out.println("Do you want to start quiz(yes/no):");
					String response = keyboardInput.readLine();
					if (response.equals("yes")) {

						try {
							Statement stmt = (Statement) conn.createStatement();
							ResultSet rs = stmt.executeQuery("Select * from question;");

							while (rs.next()) {
								System.out.println(rs.getInt("qid") + ". " + rs.getString("ques") + "\n option1 : "
										+ rs.getString("opt1") + "\n option2 : " + rs.getString("opt2")
										+ "\n option3 : " + rs.getString("opt3") + "\n option4 : "
										+ rs.getString("opt4"));
								System.out.println("enter your option:");
								String answered = keyboardInput.readLine();
								if (answered.equals(rs.getString("correct"))) {
									System.out.println("correct answer");
									truecount++;
								} else {
									System.out.println("false answer");
									falsecount++;
								}
							}
							int a = truecount;
							int b = falsecount;
							System.out.println("Do you want to submit(yes/no)?");
							String submitresponse = keyboardInput.readLine();
							if (submitresponse.equals("yes")) {
								System.out.println("Correct answers:" + a + ", False answers:" + b);
								System.out.println("Accuracy:" + (a * 100 / (a + b)) + "%");
							}
						} catch (SQLException e) {
							e.printStackTrace();
						}
					}
				}

			} else {
				System.out.println("Wrong choice");
			}
		} else {
			System.out.println("Invalid Credentials. Try again");
		}
		scanner.close();

	}

}
