package firstjdbc;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map.Entry;
import java.util.Scanner;

public class FirstJdbc {

	public static void main(String[] args) {
		
		    String url ="jdbc:mysql://localhost:3306/sampledb"; 	        
	        String user = "root";
	        String password = "Welcome123";
	        
	        Connection conn = null;
			try {
				conn = DriverManager.getConnection(url, user, password);
			} catch (SQLException e) {
				e.printStackTrace();
			}
	        System.out.println("Successfully connected");
	        
	        //insert operation
	        //int age;
	        //String name;
	        Scanner scanner = new Scanner(System.in);
	       // System.out.print("enter age:");
	       // age = scanner.nextInt();
	        /*System.out.print("enter name:");
	        name= scanner.next();*/
	        scanner.close();
	        Statement stmt = null;
			try {
				stmt = conn.createStatement();
			} catch (SQLException e) {
				e.printStackTrace();
			}
	       /* int rows = 0;
			try {
			
				PreparedStatement ps = (PreparedStatement) conn.prepareStatement("INSERT INTO employee (id,age, name) VALUES (?, ?, ?)");
				
				int autoGeneratedID = 0;
				
				ps.setInt(1,autoGeneratedID);
				ps.setInt(2, age);
				ps.setString(3, name);
				 
				ps.executeUpdate();
				rows++;

			} catch (SQLException e) {
				e.printStackTrace();
			}
	        System.out.println("Rows inserted = "+ rows);*/
	        
	        //update operation
	        /*try {
				rows= stmt.executeUpdate("Update employee set age=31 where name='James'");
			} catch (SQLException e) {
				e.printStackTrace();
			}
	        System.out.println("Rows updated = "+ rows);*/
	        
	        //read operation
	        ResultSet rs = null;
			try {
				rs = stmt.executeQuery("Select * from employee where name ='shivam'");
			} catch (SQLException e) {
				e.printStackTrace();
			}
			 HashMap<Integer,Integer> hm=new HashMap<Integer,Integer>();  
	         try {
				while(rs.next()){
					hm.put(rs.getInt("id"),rs.getInt("age"));
					  for(Entry<Integer, Integer> m:hm.entrySet()){  
						   System.out.println("id:"+m.getKey()+" "+"Age:"+m.getValue());  
						  }  
				   // System.out.println("Emp Id : " + rs.getInt("id") + ", Name : " + rs.getString("name") + ", Age : " + rs.getInt("age"));
				}
			} catch (SQLException e) {
				e.printStackTrace();
			}
	        
	        //delete operation
	        /*try {
				rows = stmt.executeUpdate("delete from employee where name = 'James'");
			} catch (SQLException e) {
				e.printStackTrace();
			}
	        System.out.println("Rows deleted = "+ rows);*/
	    
	}
}